
server:
  #  servlet:
  #    context-path: /api
  port: 9999

spring:
  #  jackson:
  #    time-zone: GMT+8


  datasource:
    driver-class-name: org.postgresql.Driver
    username: username
    password: root
    url: jdbc:postgresql://localhost:5432/message?useSSL=false

  devtools:
    restart:
      additional-paths: ./src/main
      enabled: true

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.shu.message.model.entity


graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  tools:
    schemaLocationPattern: "**/*.graphqls"


graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true